@baseUrl = http://localhost:3000

# MESSAGES
###
GET {{baseUrl}}/messages/

###
GET {{baseUrl}}/messages/1/

###
POST {{baseUrl}}/messages/
Content-Type: application/json

{
  "message": "Este é o recado que estou enviando",
  "nova chave": "outro valor"
}

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### ExemploDeRota

# @name ExemploDeRota
GET {{baseUrl}}/home/exemplo/

### ConceitosManualController Home

# @name ConceitosManualControllerHome
GET {{baseUrl}}/conceitos-manual/

### ConceitosAutomaticoController Home

# @name ConceitosAutomaticoControllerHome
GET {{baseUrl}}/conceitos-automatico/
